name: Release pg_auto_dw

defaults:
  run:
    shell: bash
    working-directory: ./extension

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  release:
    types:
      - created
jobs:
  publish:
    # if: github.event_name == 'release'
    name: trunk publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: [14, 15, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install stoml and pg-trunk
        shell: bash
        run: |
          set -xe
          wget https://github.com/freshautomations/stoml/releases/download/v0.7.1/stoml_linux_amd64 &> /dev/null
          mv stoml_linux_amd64 stoml
          chmod +x stoml
          sudo mv stoml /usr/local/bin/
          cargo install pg-trunk
      - name: trunk build
        working-directory: ./extension
        run: |
          ~/.cargo/bin/trunk build --pg-version ${{ matrix.pg-version }}
      - name: trunk publish
        working-directory: ./extension
        env:
          TRUNK_API_TOKEN: ${{ secrets.TRUNK_AUTH_TOKEN }}
        run: ~/.cargo/bin/trunk publish
